language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-27
    
before_script:
  - cd android
  #- bash download_plugins.sh

script:
  - bash ./gradlew assemble