language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-28.0.1
    
    - android-27
    
before_script:
  - cd android
  - sudo ./download_plugins

script:
  - sudo ./gradlew assemble